server:
  # 端口
  port: 8670

# Spring配置
spring:
  application:
    name: blog
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: @profiles.active@
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
# swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  path: /swagger-ui.html
  info:
    # 标题
    title: '标题：hyde-blog接口文档'
    # 描述
    description: '描述：用于管理个人博客的各个模块信息'
    # 版本
    version: '版本号: 1'
    # 作者信息
    contact:
      name: hyde
      email: 1719317647@qq.com






